# Generated by Django 2.2.4 on 2019-08-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_parity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ip',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
